//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： General.xlsx
// </auto-generated>
//--------------------------------------------------

class GeneralConfig extends ConfigDataBase
{
	/**武将名*/
	public get Name():string {  return this.Get<string>("Name"); }

	/**武将属国*/
	public get CountryId():number {  return this.Get<number>("CountryId"); }

	/**对应点数*/
	public get Point():number {  return this.Get<number>("Point"); }

	/**资源名*/
	public get Res():string {  return this.Get<string>("Res"); }

	/**武将描述*/
	public get Discribe():string {  return this.Get<string>("Discribe"); }

	/**初始星级*/
	public get InitStar():number {  return this.Get<number>("InitStar"); }

	/**星级上限*/
	public get MaxStar():number {  return this.Get<number>("MaxStar"); }

	/**攻击*/
	public get Attack():number {  return this.Get<number>("Attack"); }

	/**血量*/
	public get Hp():number {  return this.Get<number>("Hp"); }

}
