//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Hegemony.xlsx
// </auto-generated>
//--------------------------------------------------

class HegemonyConfig extends ConfigDataBase
{
	/**类型*/
	public get Type():number {  return this.Get<number>("Type"); }

	/**魔晶奖励*/
	public get Award():number {  return this.Get<number>("Award"); }

	/**参赛费用*/
	public get Cost():number {  return this.Get<number>("Cost"); }

	/**参赛人数*/
	public get Member():number {  return this.Get<number>("Member"); }

	/**收益*/
	public get Earning():number {  return this.Get<number>("Earning"); }

	/**升级场次*/
	public get Upgrade():number {  return this.Get<number>("Upgrade"); }

}
