//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Office.xlsx
// </auto-generated>
//--------------------------------------------------

class OfficeConfig extends ConfigDataBase
{
	/**武将名*/
	public get Name():string {  return this.Get<string>("Name"); }

	/**需经验*/
	public get Exp():number {  return this.Get<number>("Exp"); }

	/**头像框资源名称*/
	public get Res():string {  return this.Get<string>("Res"); }

}
