//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Skill.xlsx
// </auto-generated>
//--------------------------------------------------

class SkillConfig extends ConfigDataBase
{
	/**类型*/
	public get Type():number {  return this.Get<number>("Type"); }

	/**技能名称*/
	public get Name():string {  return this.Get<string>("Name"); }

	/**技能伤害*/
	public get Damage():number {  return this.Get<number>("Damage"); }

	/**资源名*/
	public get Res():string {  return this.Get<string>("Res"); }

	/**最低技能奖励*/
	public get MinAward():number {  return this.Get<number>("MinAward"); }

	/**最高技能奖励*/
	public get MaxAward():number {  return this.Get<number>("MaxAward"); }

	/**奖励概率*/
	public get AwardRate():number {  return this.Get<number>("AwardRate"); }

}
