//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： TigerDragon.xlsx
// </auto-generated>
//--------------------------------------------------

class TigerDragonConfig extends ConfigDataBase
{
	/**战场名*/
	public get Name():string {  return this.Get<string>("Name"); }

	/**获胜功勋值奖励*/
	public get AddExp():number[][] {  return this.Get<number[][]>("AddExp"); }

	/**失败功勋值减少*/
	public get SubExp():number[][] {  return this.Get<number[][]>("SubExp"); }

	/**固定功勋值奖励*/
	public get AwardExp():number[][] {  return this.Get<number[][]>("AwardExp"); }

	/**获胜积攒能量值*/
	public get AddEnergy():number[][] {  return this.Get<number[][]>("AddEnergy"); }

	/**失败积攒能量值*/
	public get FailEnergy():number {  return this.Get<number>("FailEnergy"); }

	/**出征费用*/
	public get Cost():number {  return this.Get<number>("Cost"); }

	/**进入下限*/
	public get MinCondition():number {  return this.Get<number>("MinCondition"); }

	/**进入上限*/
	public get MaxCondition():number {  return this.Get<number>("MaxCondition"); }

}
