# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='game',
  syntax='proto3',
  serialized_pb=_b('\n\ngame.proto\x12\x04game\"{\n\x06Player\x12\x0c\n\x04seat\x18\x01 \x01(\r\x12\x0e\n\x06player\x18\x02 \x01(\t\x12\x0c\n\x04info\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\r\x12\x11\n\tis_online\x18\x05 \x01(\r\x12\x13\n\x0btotal_score\x18\x06 \x01(\x05\x12\r\n\x05state\x18\x07 \x01(\t\"\x80\x01\n\x11\x43reateRoomRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\r\x12\x12\n\nowner_uuid\x18\x02 \x01(\t\x12\x0e\n\x06kwargs\x18\x03 \x01(\t\x12\x11\n\troom_uuid\x18\x04 \x01(\t\x12\x0f\n\x07\x63lub_id\x18\x05 \x01(\r\x12\x12\n\nowner_info\x18\x06 \x01(\t\"\"\n\x12\x43reateRoomResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\"A\n\x10\x45nterRoomRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\r\x12\x0e\n\x06player\x18\x02 \x01(\t\x12\x0c\n\x04info\x18\x03 \x01(\t\"\xaa\x01\n\x11\x45nterRoomResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07room_id\x18\x02 \x01(\r\x12\r\n\x05owner\x18\x03 \x01(\t\x12\x0e\n\x06kwargs\x18\x04 \x01(\t\x12\x12\n\nrest_cards\x18\x05 \x01(\r\x12\x1c\n\x06player\x18\x06 \x03(\x0b\x32\x0c.game.Player\x12\x12\n\nowner_info\x18\x07 \x01(\t\x12\x11\n\troom_type\x18\x08 \x01(\rb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='game.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seat', full_name='game.Player.seat', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='game.Player.player', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='game.Player.info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='game.Player.status', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_online', full_name='game.Player.is_online', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_score', full_name='game.Player.total_score', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='game.Player.state', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=143,
)


_CREATEROOMREQUEST = _descriptor.Descriptor(
  name='CreateRoomRequest',
  full_name='game.CreateRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_id', full_name='game.CreateRoomRequest.room_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_uuid', full_name='game.CreateRoomRequest.owner_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='game.CreateRoomRequest.kwargs', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_uuid', full_name='game.CreateRoomRequest.room_uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='club_id', full_name='game.CreateRoomRequest.club_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_info', full_name='game.CreateRoomRequest.owner_info', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=274,
)


_CREATEROOMRESPONSE = _descriptor.Descriptor(
  name='CreateRoomResponse',
  full_name='game.CreateRoomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='game.CreateRoomResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=310,
)


_ENTERROOMREQUEST = _descriptor.Descriptor(
  name='EnterRoomRequest',
  full_name='game.EnterRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_id', full_name='game.EnterRoomRequest.room_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='game.EnterRoomRequest.player', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='game.EnterRoomRequest.info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=377,
)


_ENTERROOMRESPONSE = _descriptor.Descriptor(
  name='EnterRoomResponse',
  full_name='game.EnterRoomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='game.EnterRoomResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='game.EnterRoomResponse.room_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='game.EnterRoomResponse.owner', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='game.EnterRoomResponse.kwargs', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rest_cards', full_name='game.EnterRoomResponse.rest_cards', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='game.EnterRoomResponse.player', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_info', full_name='game.EnterRoomResponse.owner_info', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_type', full_name='game.EnterRoomResponse.room_type', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=550,
)

_ENTERROOMRESPONSE.fields_by_name['player'].message_type = _PLAYER
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['CreateRoomRequest'] = _CREATEROOMREQUEST
DESCRIPTOR.message_types_by_name['CreateRoomResponse'] = _CREATEROOMRESPONSE
DESCRIPTOR.message_types_by_name['EnterRoomRequest'] = _ENTERROOMREQUEST
DESCRIPTOR.message_types_by_name['EnterRoomResponse'] = _ENTERROOMRESPONSE

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.Player)
  ))
_sym_db.RegisterMessage(Player)

CreateRoomRequest = _reflection.GeneratedProtocolMessageType('CreateRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEROOMREQUEST,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.CreateRoomRequest)
  ))
_sym_db.RegisterMessage(CreateRoomRequest)

CreateRoomResponse = _reflection.GeneratedProtocolMessageType('CreateRoomResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEROOMRESPONSE,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.CreateRoomResponse)
  ))
_sym_db.RegisterMessage(CreateRoomResponse)

EnterRoomRequest = _reflection.GeneratedProtocolMessageType('EnterRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _ENTERROOMREQUEST,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.EnterRoomRequest)
  ))
_sym_db.RegisterMessage(EnterRoomRequest)

EnterRoomResponse = _reflection.GeneratedProtocolMessageType('EnterRoomResponse', (_message.Message,), dict(
  DESCRIPTOR = _ENTERROOMRESPONSE,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.EnterRoomResponse)
  ))
_sym_db.RegisterMessage(EnterRoomResponse)


# @@protoc_insertion_point(module_scope)
