//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Achievement.xlsx
// </auto-generated>
//--------------------------------------------------
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var AchievementConfig = (function (_super) {
    __extends(AchievementConfig, _super);
    function AchievementConfig() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(AchievementConfig.prototype, "Name", {
        /**任务名称*/
        get: function () { return this.Get("Name"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "Describe", {
        /**任务描述*/
        get: function () { return this.Get("Describe"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "PreId", {
        /**关联任务*/
        get: function () { return this.Get("PreId"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "Star", {
        /**星级*/
        get: function () { return this.Get("Star"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "Res", {
        /**资源名称*/
        get: function () { return this.Get("Res"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "Type", {
        /**任务类型*/
        get: function () { return this.Get("Type"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "Action", {
        /**功能号*/
        get: function () { return this.Get("Action"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "Count", {
        /**取值*/
        get: function () { return this.Get("Count"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "AwardType", {
        /**奖励类型*/
        get: function () { return this.Get("AwardType"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AchievementConfig.prototype, "AwardValue", {
        /**奖励值*/
        get: function () { return this.Get("AwardValue"); },
        enumerable: true,
        configurable: true
    });
    return AchievementConfig;
}(ConfigDataBase));
__reflect(AchievementConfig.prototype, "AchievementConfig");
