//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Adviser.xlsx
// </auto-generated>
//--------------------------------------------------
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var AdviserConfig = (function (_super) {
    __extends(AdviserConfig, _super);
    function AdviserConfig() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(AdviserConfig.prototype, "Name", {
        /**武将名*/
        get: function () { return this.Get("Name"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AdviserConfig.prototype, "Level", {
        /**军师等级*/
        get: function () { return this.Get("Level"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AdviserConfig.prototype, "MineTime", {
        /**采矿时间*/
        get: function () { return this.Get("MineTime"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AdviserConfig.prototype, "UnlockType", {
        /**解锁方式*/
        get: function () { return this.Get("UnlockType"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AdviserConfig.prototype, "UnlockMoJing", {
        /**解锁魔晶*/
        get: function () { return this.Get("UnlockMoJing"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(AdviserConfig.prototype, "Res", {
        /**数据表中未注释,请检查*/
        get: function () { return this.Get("Res"); },
        enumerable: true,
        configurable: true
    });
    return AdviserConfig;
}(ConfigDataBase));
__reflect(AdviserConfig.prototype, "AdviserConfig");
