//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： General.xlsx
// </auto-generated>
//--------------------------------------------------
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var GeneralConfig = (function (_super) {
    __extends(GeneralConfig, _super);
    function GeneralConfig() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(GeneralConfig.prototype, "Name", {
        /**武将名*/
        get: function () { return this.Get("Name"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(GeneralConfig.prototype, "CountryId", {
        /**武将属国*/
        get: function () { return this.Get("CountryId"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(GeneralConfig.prototype, "Point", {
        /**对应点数*/
        get: function () { return this.Get("Point"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(GeneralConfig.prototype, "Res", {
        /**资源名*/
        get: function () { return this.Get("Res"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(GeneralConfig.prototype, "Discribe", {
        /**武将描述*/
        get: function () { return this.Get("Discribe"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(GeneralConfig.prototype, "InitStar", {
        /**初始星级*/
        get: function () { return this.Get("InitStar"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(GeneralConfig.prototype, "MaxStar", {
        /**星级上限*/
        get: function () { return this.Get("MaxStar"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(GeneralConfig.prototype, "Attack", {
        /**攻击*/
        get: function () { return this.Get("Attack"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(GeneralConfig.prototype, "Hp", {
        /**血量*/
        get: function () { return this.Get("Hp"); },
        enumerable: true,
        configurable: true
    });
    return GeneralConfig;
}(ConfigDataBase));
__reflect(GeneralConfig.prototype, "GeneralConfig");
