//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Hegemony.xlsx
// </auto-generated>
//--------------------------------------------------
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var HegemonyConfig = (function (_super) {
    __extends(HegemonyConfig, _super);
    function HegemonyConfig() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(HegemonyConfig.prototype, "Type", {
        /**类型*/
        get: function () { return this.Get("Type"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(HegemonyConfig.prototype, "Award", {
        /**魔晶奖励*/
        get: function () { return this.Get("Award"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(HegemonyConfig.prototype, "Cost", {
        /**参赛费用*/
        get: function () { return this.Get("Cost"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(HegemonyConfig.prototype, "Member", {
        /**参赛人数*/
        get: function () { return this.Get("Member"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(HegemonyConfig.prototype, "Earning", {
        /**收益*/
        get: function () { return this.Get("Earning"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(HegemonyConfig.prototype, "Upgrade", {
        /**升级场次*/
        get: function () { return this.Get("Upgrade"); },
        enumerable: true,
        configurable: true
    });
    return HegemonyConfig;
}(ConfigDataBase));
__reflect(HegemonyConfig.prototype, "HegemonyConfig");
