//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Item.xlsx
// </auto-generated>
//--------------------------------------------------
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var ItemConfig = (function (_super) {
    __extends(ItemConfig, _super);
    function ItemConfig() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(ItemConfig.prototype, "Name", {
        /**道具名称*/
        get: function () { return this.Get("Name"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(ItemConfig.prototype, "Describe", {
        /**用途描述*/
        get: function () { return this.Get("Describe"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(ItemConfig.prototype, "Type", {
        /**类型*/
        get: function () { return this.Get("Type"); },
        enumerable: true,
        configurable: true
    });
    return ItemConfig;
}(ConfigDataBase));
__reflect(ItemConfig.prototype, "ItemConfig");
