//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Level.xlsx
// </auto-generated>
//--------------------------------------------------
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var LevelConfig = (function (_super) {
    __extends(LevelConfig, _super);
    function LevelConfig() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(LevelConfig.prototype, "Level", {
        /**等级*/
        get: function () { return this.Get("Level"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(LevelConfig.prototype, "Exp", {
        /**经验*/
        get: function () { return this.Get("Exp"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(LevelConfig.prototype, "Unlock", {
        /**解锁功能*/
        get: function () { return this.Get("Unlock"); },
        enumerable: true,
        configurable: true
    });
    return LevelConfig;
}(ConfigDataBase));
__reflect(LevelConfig.prototype, "LevelConfig");
