//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Office.xlsx
// </auto-generated>
//--------------------------------------------------
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var OfficeConfig = (function (_super) {
    __extends(OfficeConfig, _super);
    function OfficeConfig() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(OfficeConfig.prototype, "Name", {
        /**武将名*/
        get: function () { return this.Get("Name"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(OfficeConfig.prototype, "Exp", {
        /**需经验*/
        get: function () { return this.Get("Exp"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(OfficeConfig.prototype, "Res", {
        /**头像框资源名称*/
        get: function () { return this.Get("Res"); },
        enumerable: true,
        configurable: true
    });
    return OfficeConfig;
}(ConfigDataBase));
__reflect(OfficeConfig.prototype, "OfficeConfig");
