//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Star.xlsx
// </auto-generated>
//--------------------------------------------------
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var StarConfig = (function (_super) {
    __extends(StarConfig, _super);
    function StarConfig() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(StarConfig.prototype, "Star", {
        /**星数*/
        get: function () { return this.Get("Star"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(StarConfig.prototype, "AddRate", {
        /**魔晶增益*/
        get: function () { return this.Get("AddRate"); },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(StarConfig.prototype, "AddJiangHun", {
        /**将魂令增益*/
        get: function () { return this.Get("AddJiangHun"); },
        enumerable: true,
        configurable: true
    });
    return StarConfig;
}(ConfigDataBase));
__reflect(StarConfig.prototype, "StarConfig");
