//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Adviser.xlsx
// </auto-generated>
//--------------------------------------------------

class AdviserConfig extends ConfigDataBase
{
	/**武将名*/
	public get Name():string {  return this.Get<string>("Name"); }

	/**军师等级*/
	public get Level():number {  return this.Get<number>("Level"); }

	/**采矿时间*/
	public get MineTime():number {  return this.Get<number>("MineTime"); }

	/**解锁方式*/
	public get UnlockType():number[] {  return this.Get<number[]>("UnlockType"); }

	/**解锁魔晶*/
	public get UnlockMoJing():number {  return this.Get<number>("UnlockMoJing"); }

	/**数据表中未注释,请检查*/
	public get Res():string {  return this.Get<string>("Res"); }

}
