//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Item.xlsx
// </auto-generated>
//--------------------------------------------------

class ItemConfig extends ConfigDataBase
{
	/**道具名称*/
	public get Name():string {  return this.Get<string>("Name"); }

	/**用途描述*/
	public get Describe():string {  return this.Get<string>("Describe"); }

	/**类型*/
	public get Type():number {  return this.Get<number>("Type"); }

}
