//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Level.xlsx
// </auto-generated>
//--------------------------------------------------

class LevelConfig extends ConfigDataBase
{
	/**等级*/
	public get Level():string {  return this.Get<string>("Level"); }

	/**经验*/
	public get Exp():number {  return this.Get<number>("Exp"); }

	/**解锁功能*/
	public get Unlock():number {  return this.Get<number>("Unlock"); }

}
