//--------------------------------------------------
// <auto-generated>
//      本文件由《纳米娱乐-游戏编辑器-数据工具》自动生成
//      源文件： Star.xlsx
// </auto-generated>
//--------------------------------------------------

class StarConfig extends ConfigDataBase
{
	/**星数*/
	public get Star():number {  return this.Get<number>("Star"); }

	/**魔晶增益*/
	public get AddRate():number {  return this.Get<number>("AddRate"); }

	/**将魂令增益*/
	public get AddJiangHun():number {  return this.Get<number>("AddJiangHun"); }

}
